# Generated by Django 4.2.7 on 2023-12-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='faction',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '-'), (2, '-'), (3, '-'), (4, '-')], null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='power',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='rarity',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Legendary'), (2, 'Epic'), (3, 'Rare'), (4, 'Common')], null=True),
        ),
    ]
