# Generated by Django 4.2.7 on 2023-12-10 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_alter_card_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='name',
            new_name='cardname',
        ),
    ]
