# Generated by Django 4.2.7 on 2023-12-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_rename_name_card_cardname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/cards'),
        ),
    ]
