# Generated by Django 4.2.7 on 2023-12-24 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0007_alter_card_faction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faction_name', models.CharField(max_length=64, unique=True)),
                ('history', models.CharField(max_length=1024)),
                ('flag', models.ImageField(blank=True, null=True, upload_to='images/factions/')),
            ],
        ),
        migrations.RemoveField(
            model_name='card',
            name='rarity',
        ),
        migrations.AlterField(
            model_name='card',
            name='faction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='card.faction'),
        ),
    ]
