# Generated by Django 4.2.7 on 2023-11-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
        ('user', '0003_alter_usermodel_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='cards',
            field=models.ManyToManyField(blank=True, to='card.card'),
        ),
    ]
