# Generated by Django 4.2.7 on 2023-12-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_usermodel_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/profiles'),
        ),
    ]
