# Generated by Django 4.2.7 on 2023-12-10 05:46

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_usermodel_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='profile_photo',
            field=models.ImageField(blank=True, default='images/profiles/default', null=True, upload_to=user.models.path_and_rename),
        ),
    ]
